# Generated by Django 5.1.2 on 2025-04-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image_baner',
            field=models.ImageField(blank=True, upload_to='img/store/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image_horizontal',
            field=models.ImageField(blank=True, upload_to='img/store/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image_vertical',
            field=models.ImageField(blank=True, upload_to='img/store/'),
        ),
    ]
