# Generated by Django 5.1.2 on 2025-04-25 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('store', '0002_alter_store_image_baner_alter_store_image_horizontal_and_more'),
        ('tax', '0003_rename_procentaje_taxes_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(max_length=256, null=True)),
                ('over_product', models.TextField(blank=True)),
                ('code_bar_product', models.CharField(max_length=255)),
                ('code_lote_product', models.CharField(blank=True, max_length=255)),
                ('stock', models.DecimalField(decimal_places=0, max_digits=10)),
                ('price_sale', models.DecimalField(decimal_places=3, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('promotion', models.BooleanField(default=False)),
                ('url_image_one_product', models.ImageField(blank=True, upload_to='img/product/')),
                ('url_image_two_product', models.ImageField(blank=True, upload_to='img/product/')),
                ('url_image_three_product', models.ImageField(blank=True, upload_to='img/product/')),
                ('material_product', models.CharField(max_length=60, null=True)),
                ('color', models.CharField(max_length=60, null=True)),
                ('garantia_product', models.CharField(max_length=80, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.categories')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.store')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tax.taxes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
