# Generated by Django 5.1.2 on 2025-04-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxes',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
