# Generated by Django 5.1.2 on 2025-04-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_alter_taxes_created_alter_taxes_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxes',
            old_name='procentaje',
            new_name='percentage',
        ),
    ]
