# Generated by Django 5.1.2 on 2025-04-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_suscription',
            field=models.BooleanField(default=True),
        ),
    ]
