# Generated by Django 5.1.2 on 2025-04-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='neighborhood',
            field=models.CharField(default='direccion', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='ruc_profile',
            field=models.CharField(default='direccion', max_length=9, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_profile',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
