# Generated by Django 5.1.2 on 2025-04-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_neighborhood_profile_ruc_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ruc_profile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
