# Generated by Django 5.1.2 on 2025-04-16 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
        ('country', '0001_initial'),
        ('department', '0002_alter_departments_options'),
        ('profiles', '0003_alter_profile_ruc_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(default=2005, on_delete=django.db.models.deletion.PROTECT, to='city.cities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(default=2005, on_delete=django.db.models.deletion.PROTECT, to='country.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(default=2005, on_delete=django.db.models.deletion.PROTECT, to='department.departments'),
            preserve_default=False,
        ),
    ]
